/**
 * Plugin peer channel packet leaf module (P4).
 *
 * Scope boundary: this file authenticates and frames a single peer packet. It
 * carries no physical peer authority and no catalog/instance admission gate —
 * deciding *which* peer may speak, which host revision is live, whether a
 * packet is `publishReady`, and every `actualTask` terminal state belongs to
 * the future host composition, not here. It opens no port and mounts no route.
 *
 * The transport keeps metadata and body separate:
 *   - header metadata is strict UTF-8 JSON, capped at {@link PEER_HEADER_MAX_BYTES},
 *     carried over HTTP as canonical base64url (no padding);
 *   - each body frame is raw bytes, capped at {@link PEER_BODY_MAX_BYTES}.
 * A future large-payload stream reuses the same 64 KiB frames; a multi-megabyte
 * body never rides a single frame and never enlarges the old RPC envelope.
 *
 * Credentials are only minted by {@link createPluginPeerCredential} from a
 * supervision process credential. The raw supervision key is never stored,
 * logged, or exported; a domain-separated derived key is held in a private
 * WeakMap brand and a bare `{ identity, process_key }` object is never accepted.
 * Other metadata parsing reuses the existing strict-JSON helpers so no getter,
 * proxy trap, `toJSON`, symbol, cycle, or non-JSON shape is ever executed.
 */
import { createHash, createHmac, timingSafeEqual } from 'node:crypto';
import { isProxy } from 'node:util/types';
import { isLowercaseUuid } from '../config-storage/validation';
import type { SupervisionProcessCredential } from '../supervision/protocol';
import { RpcProtocolError, decodeRpcJson, encodeCanonicalRpcJson, encodeRpcJson, type RpcJson } from './wire-contract';

export const PEER_PROTOCOL = 'bungee-plugin-communication/v1' as const;
/** Metadata header limit; the body budget is independent. */
export const PEER_HEADER_MAX_BYTES = 8192;
/** Raw body frame limit. Larger payloads belong to a separate future stream. */
export const PEER_BODY_MAX_BYTES = 64 * 1024;
/** Canonical unpadded base64url length of {@link PEER_HEADER_MAX_BYTES}; a pre-decode allocation guard. */
export const PEER_HEADER_MAX_BASE64URL_CHARS =
  Math.floor(PEER_HEADER_MAX_BYTES / 3) * 4
  + (PEER_HEADER_MAX_BYTES % 3 === 1 ? 2 : PEER_HEADER_MAX_BYTES % 3 === 2 ? 3 : 0);

export const PEER_REPLAY_WINDOW_DEFAULT_CAPACITY = 1024;
export const PEER_REPLAY_WINDOW_MIN_CAPACITY = 1;
export const PEER_REPLAY_WINDOW_MAX_CAPACITY = 4096;

/** Domain separation for the derived peer key. Distinct from supervision and old plugin-control. */
const PEER_KEY_DOMAIN = 'bungee-plugin-communication/v1/peer-key';

export type PluginPeerRole = 'worker' | 'ingress';
export type PluginPeerDirection = 'peer-to-control' | 'control-to-peer';
export type PluginPeerLane = 'registry' | 'rpc' | 'event' | 'snapshot' | 'stream';
export type PluginPeerKind = 'request' | 'response' | 'cancel' | 'terminal' | 'notification' | 'chunk';

export type PluginPeerIdentity = {
  readonly role: PluginPeerRole;
  readonly process_instance_id: string;
  readonly boot_nonce: string;
};

export type PluginPeerAuthority = {
  readonly controller_epoch: number;
  readonly controller_id: string;
};

export type PluginPeerHeader = {
  readonly protocol: typeof PEER_PROTOCOL;
  readonly direction: PluginPeerDirection;
  readonly peer: PluginPeerIdentity;
  readonly authority: PluginPeerAuthority;
  readonly sequence: number;
  readonly request_id: string;
  readonly lane: PluginPeerLane;
  readonly kind: PluginPeerKind;
  readonly deadline_at: number;
  /** Host-authored metadata; typed service-specific validation happens later. */
  readonly context: RpcJson;
  readonly body_hash: `sha256:${string}`;
  readonly mac: `hmac-sha256:${string}`;
};

/**
 * Caller-supplied sign input. `protocol`, `peer`, `body_hash`, and `mac` are
 * always generated by the factory from the credential and the raw body.
 */
export type PluginPeerUnsignedFields = {
  readonly direction: PluginPeerDirection;
  readonly authority: PluginPeerAuthority;
  readonly sequence: number;
  readonly request_id: string;
  readonly lane: PluginPeerLane;
  readonly kind: PluginPeerKind;
  readonly deadline_at: number;
  readonly context: RpcJson;
};

export type PluginPeerPacket = {
  readonly header: PluginPeerHeader;
  readonly body: Uint8Array;
};

export type PluginPeerExpectation = {
  readonly direction: PluginPeerDirection;
  readonly authority: PluginPeerAuthority;
};

/** Public half of a peer credential: only the frozen public identity, never a key. */
export type PluginPeerCredential = {
  readonly identity: PluginPeerIdentity;
};

export type PluginPeerProtocolErrorCode =
  | 'malformed_message'
  | 'unsupported_protocol'
  | 'size_limit'
  | 'invalid_credential'
  | 'identity_mismatch'
  | 'authority_mismatch'
  | 'direction_mismatch'
  | 'authentication_failed'
  | 'replayed';

/** Fixed-code error. It never carries a cause, payload, secret, or signing body. */
export class PluginPeerProtocolError extends Error {
  readonly name = 'PluginPeerProtocolError';

  constructor(
    readonly code: PluginPeerProtocolErrorCode,
    message: string,
  ) {
    super(message);
  }
}

type PeerCredentialRecord = {
  readonly key: Uint8Array;
  readonly identity: PluginPeerIdentity;
};

const PEER_CREDENTIALS = new WeakMap<object, PeerCredentialRecord>();

const ROLES = new Set<PluginPeerRole>(['worker', 'ingress']);
const DIRECTIONS = new Set<PluginPeerDirection>(['peer-to-control', 'control-to-peer']);
const LANES = new Set<PluginPeerLane>(['registry', 'rpc', 'event', 'snapshot', 'stream']);
const KINDS = new Set<PluginPeerKind>(['request', 'response', 'cancel', 'terminal', 'notification', 'chunk']);
const DIGEST = /^sha256:[0-9a-f]{64}$/;
const MAC = /^hmac-sha256:[0-9a-f]{64}$/;
const BASE64URL = /^[A-Za-z0-9_-]+$/;

const HEADER_KEYS = [
  'protocol', 'direction', 'peer', 'authority', 'sequence', 'request_id',
  'lane', 'kind', 'deadline_at', 'context', 'body_hash', 'mac',
] as const;
const UNSIGNED_FIELD_KEYS = [
  'direction', 'authority', 'sequence', 'request_id', 'lane', 'kind', 'deadline_at', 'context',
] as const;
const EXPECTATION_KEYS = ['direction', 'authority'] as const;
const IDENTITY_KEYS = ['role', 'process_instance_id', 'boot_nonce'] as const;
const AUTHORITY_KEYS = ['controller_epoch', 'controller_id'] as const;

function fail(code: PluginPeerProtocolErrorCode, message: string): never {
  throw new PluginPeerProtocolError(code, message);
}

function malformed(message: string): never {
  fail('malformed_message', message);
}

/**
 * Strictly clones an input into bounded pure JSON without ever reading an
 * accessor. The existing wire-contract encoder inspects own property
 * descriptors first, rejects proxies, symbols, cycles, `toJSON`, non-finite
 * numbers, lone surrogates, and over-deep nesting, and enforces the byte bound.
 */
function boundedJsonClone(value: unknown, maxBytes: number = PEER_HEADER_MAX_BYTES): RpcJson {
  try {
    return JSON.parse(encodeRpcJson(value, maxBytes)) as RpcJson;
  } catch (error) {
    if (error instanceof RpcProtocolError && error.code === 'size_limit') {
      return fail('size_limit', 'peer metadata exceeds its byte limit');
    }
    return malformed('peer metadata is not side-effect-free pure JSON');
  }
}

/** RPC metadata is not configuration JSON: reserved property names remain data. */
function canonicalJson(value: unknown): string {
  try { return encodeCanonicalRpcJson(value, PEER_HEADER_MAX_BYTES); }
  catch (error) {
    if (error instanceof RpcProtocolError && error.code === 'size_limit') fail('size_limit', 'peer metadata exceeds its byte limit');
    return malformed('peer metadata is not side-effect-free pure JSON');
  }
}

function asRecord(value: unknown, field: string): Record<string, unknown> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    return malformed(`${field} must be an object`);
  }
  const prototype = Object.getPrototypeOf(value);
  if (prototype !== Object.prototype && prototype !== null) {
    return malformed(`${field} must be a plain object`);
  }
  return value as Record<string, unknown>;
}

function exactKeys(input: Record<string, unknown>, fields: readonly string[], field: string): void {
  const actual = Object.keys(input);
  if (actual.length !== fields.length || actual.some((key) => !fields.includes(key))) {
    return malformed(`${field} has unexpected or missing fields`);
  }
  for (const key of fields) {
    if (!Object.prototype.hasOwnProperty.call(input, key)) {
      return malformed(`${field} has unexpected or missing fields`);
    }
  }
}

function integerField(input: Record<string, unknown>, key: string, minimum: number): number {
  const value = input[key];
  if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < minimum) {
    return malformed(`${key} must be a safe integer`);
  }
  return value;
}

function uuidField(input: Record<string, unknown>, key: string): string {
  const value = input[key];
  if (typeof value !== 'string' || !isLowercaseUuid(value)) {
    return malformed(`${key} must be a lowercase UUID`);
  }
  return value;
}

function parseRole(value: unknown): PluginPeerRole {
  if (typeof value !== 'string' || !ROLES.has(value as PluginPeerRole)) {
    return malformed('peer role must be worker or ingress');
  }
  return value as PluginPeerRole;
}

function parseDirection(value: unknown): PluginPeerDirection {
  if (typeof value !== 'string' || !DIRECTIONS.has(value as PluginPeerDirection)) {
    return malformed('direction is invalid');
  }
  return value as PluginPeerDirection;
}

function parseLane(value: unknown): PluginPeerLane {
  if (typeof value !== 'string' || !LANES.has(value as PluginPeerLane)) {
    return malformed('lane is invalid');
  }
  return value as PluginPeerLane;
}

function parseKind(value: unknown): PluginPeerKind {
  if (typeof value !== 'string' || !KINDS.has(value as PluginPeerKind)) {
    return malformed('kind is invalid');
  }
  return value as PluginPeerKind;
}

function parsePeerIdentity(value: unknown): PluginPeerIdentity {
  const input = asRecord(boundedJsonClone(value), 'peer');
  exactKeys(input, IDENTITY_KEYS, 'peer');
  return Object.freeze({
    role: parseRole(input.role),
    process_instance_id: uuidField(input, 'process_instance_id'),
    boot_nonce: uuidField(input, 'boot_nonce'),
  });
}

function parsePeerAuthority(value: unknown): PluginPeerAuthority {
  const input = asRecord(boundedJsonClone(value), 'authority');
  exactKeys(input, AUTHORITY_KEYS, 'authority');
  return Object.freeze({
    controller_epoch: integerField(input, 'controller_epoch', 0),
    controller_id: uuidField(input, 'controller_id'),
  });
}

function parseDigest(input: Record<string, unknown>, key: string): `sha256:${string}` {
  const value = input[key];
  if (typeof value !== 'string' || !DIGEST.test(value)) {
    return malformed('body_hash must be a sha256 hex digest');
  }
  return value as `sha256:${string}`;
}

function parseMac(input: Record<string, unknown>, key: string): `hmac-sha256:${string}` {
  const value = input[key];
  if (typeof value !== 'string' || !MAC.test(value)) {
    return malformed('mac must be an hmac-sha256 hex value');
  }
  return value as `hmac-sha256:${string}`;
}

function deepFreeze<T>(value: T): T {
  if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) {
    for (const child of Object.values(value as Record<string, unknown>)) deepFreeze(child);
    Object.freeze(value);
  }
  return value;
}

function assertHeaderSize(header: PluginPeerHeader): void {
  if (Buffer.byteLength(canonicalJson(header), 'utf8') > PEER_HEADER_MAX_BYTES) {
    fail('size_limit', 'peer header exceeds the metadata byte limit');
  }
}

function readDataProperty(input: object, key: string): unknown {
  if (isProxy(input)) return fail('invalid_credential', 'peer credential is invalid');
  const descriptor = Object.getOwnPropertyDescriptor(input, key);
  if (descriptor === undefined || !('value' in descriptor)) {
    return fail('invalid_credential', 'peer credential is invalid');
  }
  return descriptor.value;
}

/**
 * The sole minter. Validates the supervision credential, copies its key before
 * derivation so a later caller mutation cannot change the credential, and keeps
 * the derived key in a private WeakMap. The public object only exposes a frozen
 * public identity.
 */
export function createPluginPeerCredential(supervision: SupervisionProcessCredential): PluginPeerCredential {
  if (typeof supervision !== 'object' || supervision === null) {
    return fail('invalid_credential', 'supervision credential is invalid');
  }
  let identity: PluginPeerIdentity;
  try {
    identity = parsePeerIdentity(readDataProperty(supervision, 'identity'));
  } catch (error) {
    if (error instanceof PluginPeerProtocolError) {
      return fail('invalid_credential', 'supervision credential identity is invalid');
    }
    throw error;
  }
  const processKey = readDataProperty(supervision, 'process_key');
  if (!(processKey instanceof Uint8Array) || processKey.byteLength !== 32) {
    return fail('invalid_credential', 'supervision process key must be exactly 32 bytes');
  }
  const keyCopy = new Uint8Array(processKey);
  const derived = new Uint8Array(createHmac('sha256', keyCopy)
    .update([PEER_KEY_DOMAIN, canonicalJson(identity)].join('\0'), 'utf8')
    .digest());
  const credential: PluginPeerCredential = Object.freeze({ identity });
  PEER_CREDENTIALS.set(credential, { key: derived, identity });
  return credential;
}

function requireCredential(value: PluginPeerCredential): PeerCredentialRecord {
  if (typeof value !== 'object' || value === null) {
    return fail('invalid_credential', 'peer credential is not a module-issued credential');
  }
  const record = PEER_CREDENTIALS.get(value as object);
  if (record === undefined) {
    return fail('invalid_credential', 'peer credential is not a module-issued credential');
  }
  return record;
}

function requireBody(value: unknown): Uint8Array {
  if (!(value instanceof Uint8Array)) {
    return malformed('body must be a Uint8Array');
  }
  if (value.byteLength > PEER_BODY_MAX_BYTES) {
    return fail('size_limit', 'body exceeds the frame byte limit');
  }
  return value;
}

function macText(bytes: Uint8Array): `hmac-sha256:${string}` {
  return `hmac-sha256:${Buffer.from(bytes).toString('hex')}`;
}

function computeMac(unsigned: PluginPeerHeader | Omit<PluginPeerHeader, 'mac'>, key: Uint8Array): Uint8Array {
  return new Uint8Array(createHmac('sha256', key).update(canonicalJson(unsigned), 'utf8').digest());
}

/** SHA-256 over the exact raw body bytes; never a re-canonicalized JSON form. */
export function hashPluginPeerBody(body: Uint8Array): `sha256:${string}` {
  const bytes = requireBody(body);
  return `sha256:${createHash('sha256').update(bytes).digest('hex')}`;
}

function parseUnsignedFields(value: unknown): PluginPeerUnsignedFields {
  const input = asRecord(boundedJsonClone(value), 'fields');
  exactKeys(input, UNSIGNED_FIELD_KEYS, 'fields');
  return Object.freeze({
    direction: parseDirection(input.direction),
    authority: parsePeerAuthority(input.authority),
    sequence: integerField(input, 'sequence', 1),
    request_id: uuidField(input, 'request_id'),
    lane: parseLane(input.lane),
    kind: parseKind(input.kind),
    deadline_at: integerField(input, 'deadline_at', 1),
    context: input.context as RpcJson,
  });
}

/**
 * Signs one peer packet. Only {@link PluginPeerUnsignedFields} plus the raw body
 * are accepted; protocol, peer, body_hash and mac are derived. The returned body
 * is a copy so mutating the caller's buffer afterwards cannot change the signed
 * payload.
 */
export function signPluginPeerPacket(
  fields: PluginPeerUnsignedFields,
  body: Uint8Array,
  credential: PluginPeerCredential,
): PluginPeerPacket {
  const record = requireCredential(credential);
  const bodyBytes = new Uint8Array(requireBody(body));
  const checked = parseUnsignedFields(fields);
  const unsigned = {
    protocol: PEER_PROTOCOL,
    direction: checked.direction,
    peer: record.identity,
    authority: checked.authority,
    sequence: checked.sequence,
    request_id: checked.request_id,
    lane: checked.lane,
    kind: checked.kind,
    deadline_at: checked.deadline_at,
    context: checked.context,
    body_hash: hashPluginPeerBody(bodyBytes),
  };
  const mac = macText(computeMac(unsigned, record.key));
  const header = deepFreeze({ ...unsigned, mac }) as PluginPeerHeader;
  assertHeaderSize(header);
  return Object.freeze({ header, body: bodyBytes });
}

/** Parses and deep-freezes header metadata. No MAC verification. */
export function parsePluginPeerHeader(value: unknown): PluginPeerHeader {
  const input = asRecord(boundedJsonClone(value), 'header');
  exactKeys(input, HEADER_KEYS, 'header');
  if (input.protocol !== PEER_PROTOCOL) {
    return fail('unsupported_protocol', 'unsupported peer protocol');
  }
  const header: PluginPeerHeader = {
    protocol: PEER_PROTOCOL,
    direction: parseDirection(input.direction),
    peer: parsePeerIdentity(input.peer),
    authority: parsePeerAuthority(input.authority),
    sequence: integerField(input, 'sequence', 1),
    request_id: uuidField(input, 'request_id'),
    lane: parseLane(input.lane),
    kind: parseKind(input.kind),
    deadline_at: integerField(input, 'deadline_at', 1),
    context: input.context as RpcJson,
    body_hash: parseDigest(input, 'body_hash'),
    mac: parseMac(input, 'mac'),
  };
  const frozen = deepFreeze(header);
  assertHeaderSize(frozen);
  return frozen;
}

/** Encodes header metadata as canonical unpadded base64url of its canonical JSON. */
export function encodePluginPeerHeader(header: PluginPeerHeader): string {
  const parsed = parsePluginPeerHeader(header);
  return Buffer.from(canonicalJson(parsed), 'utf8').toString('base64url');
}

/** Decodes a canonical base64url header with a fatal UTF-8 and byte-bound check. */
export function decodePluginPeerHeader(encoded: string): PluginPeerHeader {
  if (typeof encoded !== 'string' || encoded.length === 0) {
    return malformed('encoded peer header must be a non-empty string');
  }
  if (encoded.length > PEER_HEADER_MAX_BASE64URL_CHARS) {
    return fail('size_limit', 'encoded peer header exceeds the metadata byte limit');
  }
  if (!BASE64URL.test(encoded)) {
    return malformed('encoded peer header must be unpadded base64url');
  }
  const decoded = new Uint8Array(Buffer.from(encoded, 'base64url'));
  if (Buffer.from(decoded).toString('base64url') !== encoded) {
    return malformed('encoded peer header is not canonical base64url');
  }
  let text: string;
  try {
    text = new TextDecoder('utf-8', { fatal: true }).decode(decoded);
  } catch {
    return malformed('encoded peer header is not valid UTF-8');
  }
  let parsed: RpcJson;
  try {
    parsed = decodeRpcJson(text, PEER_HEADER_MAX_BYTES);
  } catch (error) {
    if (error instanceof RpcProtocolError && error.code === 'size_limit') {
      return fail('size_limit', 'peer header exceeds the metadata byte limit');
    }
    return malformed('peer header is not strict bounded JSON');
  }
  const header = parsePluginPeerHeader(parsed);
  if (encodePluginPeerHeader(header) !== encoded) {
    return malformed('encoded peer header is not canonical');
  }
  return header;
}

function parseExpectation(value: unknown): PluginPeerExpectation {
  const input = asRecord(boundedJsonClone(value), 'expected');
  exactKeys(input, EXPECTATION_KEYS, 'expected');
  return Object.freeze({
    direction: parseDirection(input.direction),
    authority: parsePeerAuthority(input.authority),
  });
}

function equalJson(left: unknown, right: unknown): boolean {
  return canonicalJson(left) === canonicalJson(right);
}

/**
 * Verifies one peer packet against the credential and the exact expected
 * direction/authority. MAC and body-hash mismatches share one generic error so
 * neither the expected MAC nor the signing body is distinguishable. Deadline
 * expiry is deliberately not judged here: a terminal ACK may legitimately arrive
 * after the business deadline, so admission stays with the caller.
 */
export function verifyPluginPeerPacket(
  header: unknown,
  body: unknown,
  credential: PluginPeerCredential,
  expected: PluginPeerExpectation,
): true {
  const record = requireCredential(credential);
  const bodyBytes = requireBody(body);
  const expectation = parseExpectation(expected);
  const parsed = typeof header === 'string' ? decodePluginPeerHeader(header) : parsePluginPeerHeader(header);
  if (parsed.direction !== expectation.direction) {
    return fail('direction_mismatch', 'peer packet direction does not match the expected direction');
  }
  if (!equalJson(parsed.authority, expectation.authority)) {
    return fail('authority_mismatch', 'peer packet authority does not match the expected authority');
  }
  if (!equalJson(parsed.peer, record.identity)) {
    return fail('identity_mismatch', 'peer packet identity does not match the credential');
  }
  const actualHash = Buffer.from(hashPluginPeerBody(bodyBytes).slice('sha256:'.length), 'hex');
  const declaredHash = Buffer.from(parsed.body_hash.slice('sha256:'.length), 'hex');
  if (actualHash.byteLength !== declaredHash.byteLength || !timingSafeEqual(actualHash, declaredHash)) {
    return fail('authentication_failed', 'peer packet authentication failed');
  }
  const { mac: _mac, ...unsigned } = parsed;
  const expectedMac = computeMac(unsigned, record.key);
  const actualMac = Buffer.from(parsed.mac.slice('hmac-sha256:'.length), 'hex');
  if (actualMac.byteLength !== expectedMac.byteLength || !timingSafeEqual(actualMac, expectedMac)) {
    return fail('authentication_failed', 'peer packet authentication failed');
  }
  return true;
}

export type PluginPeerReplayWindowOptions = { readonly capacity?: number };

/**
 * Per-authority/direction/peer anti-replay window. The host allocates one window
 * per authenticated peer stream; this module never shares a global window and
 * never accepts a sequence on its own — the caller must verify the packet first.
 * `accept` does not verify MACs and does not trust unknown peers.
 */
export class PluginPeerReplayWindow {
  readonly capacity: number;
  private highest = 0;
  private readonly seen = new Set<number>();

  constructor(options: PluginPeerReplayWindowOptions = {}) {
    const capacity = options.capacity ?? PEER_REPLAY_WINDOW_DEFAULT_CAPACITY;
    if (!Number.isSafeInteger(capacity)
      || capacity < PEER_REPLAY_WINDOW_MIN_CAPACITY
      || capacity > PEER_REPLAY_WINDOW_MAX_CAPACITY) {
      throw new PluginPeerProtocolError('malformed_message', 'replay window capacity is out of range');
    }
    this.capacity = capacity;
  }

  /**
   * Records an already-authenticated sequence. In-window reordering is accepted;
   * duplicates and sequences older than the window are rejected as `replayed`.
   * A large forward jump prunes the window without ever growing past capacity.
   */
  accept(sequence: number): void {
    if (typeof sequence !== 'number' || !Number.isSafeInteger(sequence) || sequence <= 0) {
      throw new PluginPeerProtocolError('malformed_message', 'replay window sequence must be a positive safe integer');
    }
    if (sequence > this.highest) {
      const lowest = sequence - this.capacity + 1;
      if (lowest > 0) {
        for (const value of this.seen) {
          if (value < lowest) this.seen.delete(value);
        }
      }
      this.highest = sequence;
      this.seen.add(sequence);
      return;
    }
    const lowest = this.highest - this.capacity + 1;
    if (sequence < lowest) {
      throw new PluginPeerProtocolError('replayed', 'peer sequence is outside the replay window');
    }
    if (this.seen.has(sequence)) {
      throw new PluginPeerProtocolError('replayed', 'peer sequence was already accepted');
    }
    this.seen.add(sequence);
  }

  /** Highest accepted sequence; a status counter that never exposes key material. */
  get highestAccepted(): number {
    return this.highest;
  }

  /** Number of retained in-window sequences; bounded by {@link capacity}. */
  get windowSize(): number {
    return this.seen.size;
  }
}
