#!/usr/bin/env bun
import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from 'fs';
import { join } from 'path';

const uiDistPath = 'packages/ui/dist';
const outputPath = 'packages/core/src/ui/assets.ts';

// 检查 UI 是否已构建
if (!existsSync(uiDistPath)) {
  console.error('❌ UI dist not found. Please run "npm run build:ui" first.');
  process.exit(1);
}

// 读取 HTML
const htmlPath = join(uiDistPath, 'index.html');
if (!existsSync(htmlPath)) {
  console.error('❌ index.html not found in UI dist.');
  process.exit(1);
}
const html = readFileSync(htmlPath, 'utf-8');

function readTextAsset(filePath: string): string {
  return readFileSync(filePath, 'utf-8');
}

function readBinaryAsset(filePath: string): string {
  return readFileSync(filePath).toString('base64');
}

// 读取 assets 目录下的所有文件
const assetsDir = join(uiDistPath, 'assets');
const assets: Record<string, string> = {};

if (existsSync(assetsDir)) {
  const assetFiles = readdirSync(assetsDir);
  for (const file of assetFiles) {
    const filePath = join(assetsDir, file);
    assets[file] = readTextAsset(filePath);
  }
}

// 读取 public 复制到 dist 根目录的文件，如 favicon 和 manifest
const publicAssets: Record<string, string> = {};
const rootFiles = readdirSync(uiDistPath);
for (const file of rootFiles) {
  const filePath = join(uiDistPath, file);
  if (file !== 'index.html' && file !== 'assets' && statSync(filePath).isFile()) {
    publicAssets[file] = readBinaryAsset(filePath);
  }
}

// 生成 TypeScript 模块
const code = `// Auto-generated by scripts/bundle-ui.ts
// Do not edit manually
import { get } from 'lodash-es';

type UIAssets = {
  html: string;
  assets: Record<string, string>;
  publicAssets: Record<string, string>;
};

export const uiAssets: UIAssets = {
  html: ${JSON.stringify(html)},
  assets: ${JSON.stringify(assets, null, 2)},
  publicAssets: ${JSON.stringify(publicAssets, null, 2)}
};

function decodeBase64Asset(content: string): Blob {
  return new Blob([Uint8Array.from(atob(content), (character) => character.charCodeAt(0))]);
}

export function getAsset(path: string): string | Blob | null {
  if (path === '/' || path === '/index.html') {
    return uiAssets.html;
  }

  // Check assets directory files
  const assetPath = path.replace(/^\\/assets\\//, '');
  const asset = get(uiAssets.assets, assetPath, null);
  if (asset) return asset;

  // Check public files
  const publicPath = path.replace(/^\\//, '');
  const publicAsset = get(uiAssets.publicAssets, publicPath, null);
  return publicAsset ? decodeBase64Asset(publicAsset) : null;
}
`;

writeFileSync(outputPath, code);
console.log('✓ UI assets bundled into Core package');
console.log(`  - HTML: ${(html.length / 1024).toFixed(2)} KB`);
console.log(`  - Assets: ${Object.keys(assets).length} files`);
console.log(`  - Public assets: ${Object.keys(publicAssets).length} files`);

const totalSize = html.length + Object.values(assets).reduce((sum, content) => sum + content.length, 0) + Object.values(publicAssets).reduce((sum, content) => sum + content.length, 0);
console.log(`  - Total: ${(totalSize / 1024).toFixed(2)} KB`);
