#!/usr/bin/env bun

import { chromium, type APIRequestContext, type Browser, type Page } from 'playwright';
import { createHash } from 'node:crypto';
import { mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { Database } from 'bun:sqlite';
import type { ConfigurationAggregateV2 } from '@jeffusion/bungee-types';
import { ConfigRepository } from '../../src/config-storage';
import {
  cleanupMaster,
  cleanupSpawnedProcesses,
  createMasterCleanupScope,
  childPids,
  createMasterFixture,
  freePort,
  isIngressProcess,
  processAlive,
  removeFixture,
  runWithCleanup,
  sourceMasterEntry,
  spawnMaster,
  waitForHealth,
  waitForWorkerPids,
  waitUntil,
} from '../fixtures/master-real-process-harness';

const WORKSPACE_ROOT = resolve(import.meta.dir, '../../../..');
const EVIDENCE_DIR = join(WORKSPACE_ROOT, '.omo/evidence/management-port-playwright-real');
const TOKEN = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';
const cleanupScope = createMasterCleanupScope();
const INITIAL_MUTATION_ID = 'a1000000-0000-4000-8000-000000000001';
const SOURCE_MUTATION_ID = 'a2000000-0000-4000-8000-000000000001';
const RETRY_REQUEST_ID = 'a3000000-0000-4000-8000-000000000001';
const DATA_PATHS = [
  '/__ui/business', '/api/business', '/health', '/favicon.ico',
  '/.well-known/appspecific/com.chrome.devtools.json', '/__ui/api/config',
] as const;

type JsonObject = Record<string, any>;
type ApiStatusMap = Record<string, number[]>;
type DataPrefixObservation = {
  path: string;
  status: number | null;
  upstream_marker: { body: string; header: string | null } | null;
  access_log_observed: boolean;
};

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

function errorText(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function sanitize(value: string): string {
  return value
    .replaceAll(TOKEN, '[redacted-token]')
    .replace(/Bearer\s+[^\s"']+/gi, 'Bearer [redacted]')
    .replace(/(secret|token|password|authorization)\s*[:=]\s*[^,;\s]+/gi, '$1=[redacted]');
}

function pathOf(url: string): string {
  try {
    return new URL(url).pathname;
  } catch {
    return url.replace(/^https?:\/\/[^/]+/, '');
  }
}

function accessLogSnapshot(accessDbPath: string, paths: readonly string[]): {
  total: number;
  byPath: Record<string, { status: number; request_type: string } | null>;
} {
  const db = new Database(accessDbPath, { readonly: true, strict: true });
  try {
    const rows = db.query(
      'SELECT path, status, request_type FROM access_logs WHERE path IN ('
        + paths.map(() => '?').join(',') + ') ORDER BY id',
    ).all(...paths) as Array<{ path: string; status: number; request_type: string }>;
    const byPath: Record<string, { status: number; request_type: string } | null> = {};
    for (const path of paths) byPath[path] = null;
    for (const row of rows) byPath[row.path] = row;
    const total = (db.query('SELECT COUNT(*) AS count FROM access_logs').get() as { count: number }).count;
    return { total, byPath };
  } finally {
    db.close();
  }
}

function recoveryEvidence(runtime: JsonObject): JsonObject {
  const publication = runtime.publication ?? {};
  return {
    operation_state: publication.operation?.state ?? null,
    recovery_state: publication.recovery?.state ?? null,
    serving_complete: publication.serving_complete ?? null,
    serving_revision: publication.serving_revision ?? null,
    target_revision: publication.target_revision ?? null,
  };
}

function operationEvidence(bytes: string | undefined): JsonObject {
  return {
    length: bytes?.length ?? null,
    sha256: bytes === undefined ? null : createHash('sha256').update(bytes).digest('hex'),
  };
}

async function requireBundledUi(): Promise<void> {
  const assetsPath = join(WORKSPACE_ROOT, 'packages/core/src/ui/assets.ts');
  try {
    await stat(assetsPath);
    const source = await readFile(assetsPath, 'utf8');
    assert(source.includes('Auto-generated by scripts/bundle-ui.ts') && source.includes('uiAssets'),
      'core UI assets are not a bundled assets.ts; build UI and bundle it before running this E2E');
  } catch (error) {
    if (error instanceof Error && error.message.includes('core UI assets')) throw error;
    throw new Error('core UI assets are missing; fail closed without generating or modifying assets.ts');
  }
}

function headers(): Record<string, string> {
  return {
    authorization: `Bearer ${TOKEN}`,
    'x-bungee-next-authorization': `Bearer ${TOKEN}`,
    'content-type': 'application/json',
  };
}

async function apiJson(
  request: APIRequestContext,
  method: 'GET' | 'POST' | 'PUT',
  url: string,
  apiStatuses: ApiStatusMap,
  body?: unknown,
): Promise<{ status: number; body: JsonObject }> {
  const response = method === 'GET'
    ? await request.get(url, { headers: { authorization: `Bearer ${TOKEN}` } })
    : method === 'POST'
      ? await request.post(url, { headers: headers(), data: JSON.stringify(body ?? {}) })
      : await request.put(url, { headers: headers(), data: JSON.stringify(body ?? {}) });
  const path = pathOf(url);
  (apiStatuses[path] ??= []).push(response.status());
  const text = await response.text();
  let parsed: unknown;
  try { parsed = JSON.parse(text); } catch { parsed = { raw: text }; }
  return { status: response.status(), body: (parsed ?? {}) as JsonObject };
}

async function pollOperation(
  request: APIRequestContext,
  managementUrl: string,
  mutationId: string,
  apiStatuses: ApiStatusMap,
): Promise<JsonObject> {
  let state: JsonObject = {};
  await waitUntil(async () => {
    const response = await apiJson(request, 'GET', `${managementUrl}/__ui/api/config/operations/${mutationId}`, apiStatuses);
    state = response.body;
    return response.status === 200 && state.operation?.state === 'converged';
  }, `configuration operation ${mutationId} did not converge`, 20_000);
  return state;
}

async function pollRuntime(
  request: APIRequestContext,
  managementUrl: string,
  apiStatuses: ApiStatusMap,
  predicate: (runtime: JsonObject) => boolean,
  message: string,
  timeoutMs = 20_000,
): Promise<JsonObject> {
  let runtime: JsonObject = {};
  await waitUntil(async () => {
    const response = await apiJson(request, 'GET', `${managementUrl}/__ui/api/config/runtime`, apiStatuses);
    runtime = response.body;
    return response.status === 200 && predicate(runtime);
  }, message, timeoutMs);
  return runtime;
}

function businessAggregate(upstreamPort: number): ConfigurationAggregateV2 {
  const serviceId = 'b1000000-0000-4000-8000-000000000001';
  const endpointId = 'b2000000-0000-4000-8000-000000000001';
  const routeIds = [
    'b3000000-0000-4000-8000-000000000001',
    'b4000000-0000-4000-8000-000000000001',
    'b6000000-0000-4000-8000-000000000001',
    'b7000000-0000-4000-8000-000000000001',
    'b8000000-0000-4000-8000-000000000001',
    'b9000000-0000-4000-8000-000000000001',
  ] as const;
  return {
    plugin_activations: [{ plugin_name: 'fixture-plugin' }],
    logical_configuration: {
      auth: { enabled: true, tokens: [TOKEN] },
      services: [{
        id: serviceId,
        position: 1,
        name: 'real-business',
        plugins: [],
        endpoints: [{
          id: endpointId,
          position: 1,
          target: `http://127.0.0.1:${upstreamPort}`,
          weight: 100,
          priority: 1,
          is_disabled: false,
          plugins: [{
            id: 'b5000000-0000-4000-8000-000000000001',
            position: 1,
            name: 'fixture-plugin',
            enabled: true,
            options: {},
          }],
        }],
      }],
      routes: DATA_PATHS.map((path, position) => ({
        id: routeIds[position],
        position,
        path,
        service_id: serviceId,
        auth: { enabled: false, tokens: [] },
        plugins: [],
      })),
      plugins: [],
    },
  };
}

async function main(): Promise<void> {
  await mkdir(EVIDENCE_DIR, { recursive: true });
  await rm(EVIDENCE_DIR, { recursive: true, force: true });
  await mkdir(EVIDENCE_DIR, { recursive: true });

  const apiStatuses: ApiStatusMap = {};
  const consoleErrors: JsonObject[] = [];
  const pageErrors: JsonObject[] = [];
  const failedRequests: JsonObject[] = [];
  const harnessErrors: string[] = [];
  const blockers: string[] = [];
  let browser: Browser | null = null;
  let page: Page | null = null;
  let fixture: Awaited<ReturnType<typeof createMasterFixture>> | null = null;
  let master: ReturnType<typeof spawnMaster> | null = null;
  let business: ReturnType<typeof Bun.serve> | null = null;
  let replacementBarrier: ReturnType<typeof Bun.serve> | null = null;
  const upstreamPaths: string[] = [];
  const upstreamUnsafeHeaders: string[] = [];
  let releaseBarrier = () => {};
  let barrierReleased = false;
  let reachedBarrier!: () => void;
  let barrierReached: Promise<void> = Promise.resolve();
  let managementPort: number | null = null;
  let publicPort: number | null = null;
  let upstreamPort: number | null = null;
  let revision = { initial: 1, configured: 1, target: 1, serving: null as number | null };
  let failure: unknown = null;
  const dataPrefixObservations: DataPrefixObservation[] = DATA_PATHS.map((path) => ({
    path,
    status: null,
    upstream_marker: null,
    access_log_observed: false,
  }));
  const cleanupSteps = {
    browser: { status: 'not_run' as const },
    master: { status: 'not_run' as const },
    replacement_barrier: { status: 'not_run' as const },
    business_upstream: { status: 'not_run' as const },
    fixture: { status: 'not_run' as const },
    spawned_processes: { status: 'not_run' as const },
  } as Record<string, { status: 'not_run' | 'passed' | 'failed'; error?: string }>;

  const results: JsonObject = {
    management: 'real',
    ports: { management: null as number | null, public: null as number | null, upstream: null as number | null },
    revision,
    api_statuses: apiStatuses,
    upstream_paths: upstreamPaths,
    upstream_unsafe_headers: upstreamUnsafeHeaders,
    data_prefixes: dataPrefixObservations,
    management_isolation: {
      before: null,
      requests: [],
      after: null,
      delta: null,
    },
    recovery: {
      runtime_before_retry: null,
      retry: null,
      old_traffic: [],
      old_traffic_count: 0,
      runtime_running: null,
      runtime_succeeded: null,
      operation_before: null,
      operation_during: null,
      operation_after: null,
    },
    processes: { master: null, ingress: [], workers: [] },
    cleanup: { steps: cleanupSteps, ingress_alive_after_cleanup: [] },
    screenshots: [] as string[],
    errors: {
      console: consoleErrors,
      page: pageErrors,
      requestfailed: failedRequests,
      harness: harnessErrors,
      blockers,
    },
  };
  const cleanupStep = async (name: string, operation: () => Promise<boolean>): Promise<void> => {
    try {
      cleanupSteps[name] = { status: await operation() ? 'passed' : 'not_run' };
    } catch (error) {
      const message = `${name} cleanup: ${sanitize(errorText(error))}`;
      cleanupSteps[name] = { status: 'failed', error: message };
      harnessErrors.push(message);
      throw error;
    }
  };

  try {
    await requireBundledUi();
    fixture = await createMasterFixture('bungee-management-port-playwright-');
    const port = await freePort(cleanupScope);
    managementPort = port;
    publicPort = port + 1;

    business = Bun.serve({
      hostname: '127.0.0.1',
      port: 0,
      fetch: (request) => {
        upstreamPaths.push(pathOf(request.url));
        request.headers.forEach((_value, name) => {
          if (name.startsWith('x-bungee-internal-') || name === 'x-bungee-next-authorization') {
            upstreamUnsafeHeaders.push(`${pathOf(request.url)}:${name}`);
          }
        });
        return new Response('real-upstream-marker', { headers: { 'x-business-marker': 'real-upstream' } });
      },
    });
    assert(business.port !== undefined, 'business fixture did not bind');
    upstreamPort = business.port;

    const pluginPath = join(fixture.pluginsPath, 'fixture-plugin');
    await writeFile(join(pluginPath, 'manifest.json'), `${JSON.stringify({
      name: 'fixture-plugin', version: '1.0.0', schemaVersion: 2,
      artifactKind: 'runtime-plugin', main: 'index.js', capabilities: ['hooks', 'dynamicRuntimeLoad'],
      uiExtensionMode: 'none', engines: { bungee: '^4.2.0' }, builtin: false,
      configSchema: [{ name: 'barrierUrl', type: 'string', label: 'Barrier', required: false }], contributes: {},
    })}\n`);
    await writeFile(join(pluginPath, 'index.js'), `export default class FixtureRecoveryPlugin {
      static name = 'fixture-plugin'; static version = '1.0.0';
      static async createHandler(config) {
        if (config.barrierUrl) {
          const response = await fetch(config.barrierUrl + '/wait', { method: 'POST' });
          if (!response.ok) throw new Error('replacement barrier rejected candidate');
        }
        return { pluginName: 'fixture-plugin', config, register() {}, destroy() {} };
      }
    }\n`);

    barrierReached = new Promise<void>((resolve) => { reachedBarrier = resolve; });
    const barrier = new Promise<void>((resolve) => {
      releaseBarrier = () => {
        if (barrierReleased) return;
        barrierReleased = true;
        resolve();
      };
    });
    replacementBarrier = Bun.serve({
      hostname: '127.0.0.1',
      port: 0,
      fetch: async (request) => {
        if (new URL(request.url).pathname !== '/wait' || request.method !== 'POST') return new Response('not found', { status: 404 });
        reachedBarrier();
        await barrier;
        return new Response('released');
      },
    });
    assert(replacementBarrier.port !== undefined, 'replacement barrier did not bind');

    master = spawnMaster(cleanupScope, sourceMasterEntry(), fixture, port);
    await waitForHealth(port, master);
    assert(master.child.pid !== undefined, 'master did not expose a PID');
    results.processes.master = master.child.pid;
    results.processes.workers = [...await waitForWorkerPids(master, 2)];
    await waitUntil(async () => {
      const children = await childPids(master!.child.pid!);
      results.processes.ingress = (await Promise.all(children.map(async (pid) =>
        await isIngressProcess(pid) ? pid : null))).filter((pid): pid is number => pid !== null);
      return results.processes.ingress.length > 0;
    }, 'master did not expose an ingress PID');
    const managementUrl = `http://127.0.0.1:${port}`;
    const publicUrl = `http://127.0.0.1:${port + 1}`;
    const request = (browserRequest: APIRequestContext | null): APIRequestContext => {
      assert(browserRequest !== null, 'browser request context is unavailable');
      return browserRequest;
    };

    browser = await chromium.launch({ headless: true });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, deviceScaleFactor: 1 });
    page = await context.newPage();
    page.on('console', (message) => {
      if (message.type() === 'error') consoleErrors.push({ text: sanitize(message.text()), location: message.location() });
    });
    page.on('pageerror', (error) => pageErrors.push({ message: sanitize(error.message), stack: sanitize(error.stack ?? '') }));
    page.on('requestfailed', (requestEvent) => failedRequests.push({
      url: pathOf(requestEvent.url()), error: sanitize(requestEvent.failure()?.errorText ?? 'unknown'),
    }));

    page.on('response', (response) => {
      const path = pathOf(response.url());
      if (path.startsWith('/__ui/api/') || path.startsWith('/api/')) (apiStatuses[path] ??= []).push(response.status());
    });

    const browserRequest = request(page.request);
    const aggregate = businessAggregate(business.port);
    const initialPut = await apiJson(browserRequest, 'PUT', `${managementUrl}/__ui/api/config`, apiStatuses, {
      expected_revision: 1,
      aggregate,
      mutation_id: INITIAL_MUTATION_ID,
    });
    assert(initialPut.status === 202, `initial real configuration PUT returned ${initialPut.status}`);
    await pollOperation(browserRequest, managementUrl, INITIAL_MUTATION_ID, apiStatuses);
    revision.configured = 2;

    const sourceAggregate: ConfigurationAggregateV2 = {
      ...aggregate,
      logical_configuration: {
        ...aggregate.logical_configuration,
        log_level: 'debug',
        services: aggregate.logical_configuration.services.map((service) => ({
          ...service,
          endpoints: service.endpoints.map((endpoint) => ({
            ...endpoint,
            plugins: endpoint.plugins.map((plugin) => ({
              ...plugin,
              options: { barrierUrl: `http://127.0.0.1:${replacementBarrier!.port}` },
            })),
          })),
        })),
      },
    };
    const injected = ConfigRepository.open(fixture.dbPath);
    try {
      const committed = injected.commit({ mutation_id: SOURCE_MUTATION_ID, expected_revision: 2, aggregate: sourceAggregate,
        kind: 'config', created_at: Date.now(), target_worker_slots: [0, 1] });
      assert(committed.kind === 'committed', 'source degraded fixture did not commit');
      injected.beginPublication(SOURCE_MUTATION_ID, Date.now());
      for (const target of [0, 1]) {
        injected.beginWorkerAttempt(SOURCE_MUTATION_ID, target, 0, 'initial', Date.now());
        injected.recordWorkerResult(SOURCE_MUTATION_ID, target, { kind: 'failed', attempt_no: 1, error: 'injected retryable failure' }, Date.now());
      }
      injected.finalizePublication(SOURCE_MUTATION_ID, {
        outcome: 'degraded', error_code: 'replacement_convergence_failed',
        error_detail: 'injected retryable failure', recovery_disposition: 'retryable',
      }, Date.now());
      const automatic = injected.getCurrentRecovery();
      assert(automatic !== null, 'source degraded fixture did not create recovery');
      injected.stopRecovery(automatic.recovery_id, automatic.attempt_count, 'fatal_source_failure', 'injected stopped state', Date.now());
      revision.target = 3;
    } finally {
      injected.close();
    }

    const sourceOperationBefore = ConfigRepository.open(fixture.dbPath);
    const operationBytesBefore = JSON.stringify(sourceOperationBefore.getOperationState(SOURCE_MUTATION_ID));
    sourceOperationBefore.close();
    results.recovery.operation_before = operationEvidence(operationBytesBefore);

    await page.goto(`${managementUrl}/__ui/#/`, { waitUntil: 'networkidle' });
    assert(await page.evaluate(() => localStorage.getItem('bungee_auth_token')) === null,
      'UI login started with a pre-seeded localStorage token');
    await page.getByTestId('page-login').waitFor({ state: 'visible', timeout: 10_000 });
    await page.locator('#token-input').fill(TOKEN);
    await page.locator('[data-testid="page-login"] button').click();
    await page.getByTestId('page-dashboard').waitFor({ state: 'visible', timeout: 15_000 });
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1_000);
    const verify = await page.evaluate(async () => {
      const token = localStorage.getItem('bungee_auth_token');
      const response = await fetch('/__ui/api/auth/verify', { headers: { authorization: `Bearer ${token ?? ''}` } });
      return { status: response.status, body: await response.json() as { success?: boolean } };
    });
    assert(verify.status === 200 && verify.body.success === true, `real auth verify returned ${verify.status}`);

    const runtimeBeforeRetry = await pollRuntime(browserRequest, managementUrl, apiStatuses,
      (runtime) => runtime.publication?.operation?.state === 'degraded'
        && runtime.publication?.recovery?.state === 'stopped'
        && runtime.publication?.serving_complete === false,
      'durable degraded stopped state was not exposed by real runtime', 10_000);
    results.recovery.runtime_before_retry = recoveryEvidence(runtimeBeforeRetry);
    assert(runtimeBeforeRetry.publication.target_revision === 3, 'runtime target revision did not expose revision 3');
    assert(await page.getByTestId('dashboard-publication-recovery').isVisible(), 'Dashboard did not show the stopped recovery bar');
    assert((await page.locator('body').innerText()).includes('/__ui/business')
      && (await page.locator('body').innerText()).includes('/api/business'),
    'Dashboard did not display the authoritative configured business routes');
    await page.screenshot({ path: join(EVIDENCE_DIR, 'dashboard-recovery-stopped.png'), fullPage: true });
    results.screenshots.push('dashboard-recovery-stopped.png');

    const retryResponse = page.waitForResponse((response) => pathOf(response.url()).endsWith(`/config/operations/${SOURCE_MUTATION_ID}/retry`)
      && response.request().method() === 'POST', { timeout: 10_000 });
    await page.getByTestId('publication-retry-button').click();
    const retryAck = await retryResponse;
    apiStatuses[pathOf(retryAck.url())] ??= [];
    assert(retryAck.status() === 202, `real retry POST returned ${retryAck.status()}`);
    const retryBody = await retryAck.json() as JsonObject;
    assert(retryBody.trigger === 'manual', 'real retry POST was not a manual recovery');
    results.recovery.retry = { status: retryAck.status(), trigger: retryBody.trigger };
    await Promise.race([
      barrierReached,
      new Promise<never>((_, reject) => setTimeout(() => reject(new Error('replacement never reached the real barrier')), 10_000)),
    ]);

    const retryStatuses = apiStatuses[`/__ui/api/config/operations/${SOURCE_MUTATION_ID}/retry`] ?? [];
    assert(retryStatuses.length === 1, `Retry was POSTed ${retryStatuses.length} times instead of once`);
    const duringBytes = ConfigRepository.open(fixture.dbPath);
    const operationBytesDuring = JSON.stringify(duringBytes.getOperationState(SOURCE_MUTATION_ID));
    results.recovery.operation_during = operationEvidence(operationBytesDuring);
    results.recovery.operation_unchanged_during = operationBytesDuring === operationBytesBefore;
    assert(results.recovery.operation_unchanged_during,
      'operation row bytes changed while recovery was blocked');
    duringBytes.close();

    for (let index = 0; index < 4; index += 1) {
      const response = await browserRequest.get(`${publicUrl}/api/business`, { headers: { authorization: `Bearer ${TOKEN}` } });
      (apiStatuses['/api/business'] ??= []).push(response.status());
      const body = await response.text();
      results.recovery.old_traffic.push({ path: '/api/business', status: response.status(), body });
      results.recovery.old_traffic_count = results.recovery.old_traffic.length;
      assert(response.status() === 200 && body === 'real-upstream-marker', 'old business marker was not continuously served during recovery');
      await Bun.sleep(100);
    }
    assert(results.recovery.old_traffic_count === 4, 'insufficient blocked-period old traffic observations');

    const runningRuntime = await pollRuntime(browserRequest, managementUrl, apiStatuses,
      (runtime) => runtime.publication?.recovery?.state === 'running'
        && runtime.publication?.serving_complete === false,
      'real retry did not expose running recovery before release', 10_000);
    results.recovery.runtime_running = recoveryEvidence(runningRuntime);
    assert(runningRuntime.publication.recovery.state === 'running', 'recovery did not enter running state');
    releaseBarrier();

    const succeededRuntime = await pollRuntime(browserRequest, managementUrl, apiStatuses,
      (runtime) => runtime.publication?.recovery?.state === 'succeeded'
        && runtime.publication?.serving_complete === true
        && runtime.publication?.serving_revision === 3,
      'real recovery did not reach serving_complete succeeded', 20_000);
    results.recovery.runtime_succeeded = recoveryEvidence(succeededRuntime);
    revision.serving = succeededRuntime.publication.serving_revision;
    const operationAfter = ConfigRepository.open(fixture.dbPath);
    const operationBytesAfter = JSON.stringify(operationAfter.getOperationState(SOURCE_MUTATION_ID));
    results.recovery.operation_after = operationEvidence(operationBytesAfter);
    results.recovery.operation_unchanged_after = operationBytesAfter === operationBytesBefore;
    assert(results.recovery.operation_unchanged_after,
      'operation row bytes changed after recovery succeeded');
    operationAfter.close();

    await page.getByTestId('dashboard-publication-recovery').waitFor({ state: 'detached', timeout: 15_000 });
    assert((await page.locator('body').innerText()).includes('/__ui/business')
      && (await page.locator('body').innerText()).includes('/api/business'),
    'Dashboard did not retain authoritative runtime routes after recovery');
    await page.screenshot({ path: join(EVIDENCE_DIR, 'dashboard-recovery-succeeded.png'), fullPage: true });
    results.screenshots.push('dashboard-recovery-succeeded.png');

    for (const path of ['/api/config', '/api/config/runtime', `/api/config/operations/${SOURCE_MUTATION_ID}`, '/__ui/api/config/runtime']) {
      const response = await browserRequest.get(`${publicUrl}${path}`, { headers: { authorization: `Bearer ${TOKEN}` } });
      (apiStatuses[path] ??= []).push(response.status());
      const body = await response.text();
      assert(!body.includes('logical_configuration') && !body.includes('committed_revision'),
        `public port exposed management data at ${path}`);
    }

    for (const path of DATA_PATHS) {
      const observation = dataPrefixObservations.find((item) => item.path === path)!;
      const response = await browserRequest.get(`${publicUrl}${path}`, {
        headers: {
          authorization: `Bearer ${TOKEN}`,
          'x-bungee-next-authorization': `Bearer ${TOKEN}`,
          'x-bungee-internal-forged': 'must-not-forward',
        },
      });
      (apiStatuses[path] ??= []).push(response.status());
      const body = await response.text();
      observation.status = response.status();
      observation.upstream_marker = {
        body,
        header: response.headers()['x-business-marker'] ?? null,
      };
      assert(response.status() === 200 && body === 'real-upstream-marker',
        `public ${path} did not return the real upstream marker`);
    }

    let accessBefore: ReturnType<typeof accessLogSnapshot> | null = null;
    await waitUntil(() => {
      try {
        accessBefore = accessLogSnapshot(fixture!.accessDbPath, DATA_PATHS);
        return DATA_PATHS.every((path) => accessBefore!.byPath[path] !== null);
      } catch {
        return false;
      }
    }, 'public data-prefix requests did not produce access logs', 10_000);
    assert(accessBefore !== null, 'access-log baseline was not observed');
    const observedAccessBefore = accessBefore as ReturnType<typeof accessLogSnapshot>;
    results.management_isolation.before = {
      upstream_hits: upstreamPaths.length,
      worker_hits: observedAccessBefore.total,
    };

    for (const path of DATA_PATHS) {
      const response = await browserRequest.get(`${managementUrl}${path}`, { headers: { authorization: `Bearer ${TOKEN}` } });
      (apiStatuses[path] ??= []).push(response.status());
      results.management_isolation.requests.push({ path, status: response.status() });
      await response.text();
    }
    const accessAfter = accessLogSnapshot(fixture.accessDbPath, DATA_PATHS);
    results.management_isolation.after = {
      upstream_hits: upstreamPaths.length,
      worker_hits: accessAfter.total,
    };
    results.management_isolation.delta = {
      upstream_hits: upstreamPaths.length - results.management_isolation.before.upstream_hits,
      worker_hits: accessAfter.total - results.management_isolation.before.worker_hits,
    };
    assert(results.management_isolation.delta.upstream_hits === 0,
      'management Dashboard/API traffic reached the data-port upstream');
    assert(results.management_isolation.delta.worker_hits === 0,
      'management Dashboard/API traffic reached a worker');
    assert(upstreamUnsafeHeaders.length === 0,
      `client internal headers reached the upstream: ${upstreamUnsafeHeaders.join(', ')}`);

    for (const path of DATA_PATHS) {
      const row = accessAfter.byPath[path];
      const observation = dataPrefixObservations.find((item) => item.path === path)!;
      observation.access_log_observed = row?.status === 200 && row.request_type === 'final';
    }
    assert(dataPrefixObservations.every((observation) => observation.access_log_observed),
      'data-port requests did not produce normal access logs');

    assert(consoleErrors.length === 0, `browser console errors: ${JSON.stringify(consoleErrors)}`);
    assert(pageErrors.length === 0, `browser page errors: ${JSON.stringify(pageErrors)}`);
    assert(failedRequests.length === 0, `browser request failures: ${JSON.stringify(failedRequests)}`);
    assert(blockers.length === 0, blockers[0] ?? 'E2E blocker');
  } catch (error) {
    failure = error;
    harnessErrors.push(sanitize(errorText(error)));
  }

  try {
    await runWithCleanup(
      async () => { if (failure !== null) throw failure; },
      async () => {
        releaseBarrier();
        const cleanupResults = await Promise.allSettled([
          cleanupStep('browser', async () => {
            if (browser === null) return false;
            await browser.close();
            return true;
          }),
          cleanupStep('replacement_barrier', async () => {
            if (replacementBarrier === null) return false;
            await replacementBarrier.stop(true);
            return true;
          }),
          cleanupStep('business_upstream', async () => {
            if (business === null) return false;
            await business.stop(true);
            return true;
          }),
        ]);
        const masterResult = await Promise.allSettled([cleanupStep('master', async () => {
          if (master === null) return false;
          await cleanupMaster(master);
          return true;
        })]);
        const spawnedResult = await Promise.allSettled([cleanupStep('spawned_processes', async () => {
          await cleanupSpawnedProcesses(cleanupScope);
          return true;
        })]);
        const failures = [...cleanupResults, ...masterResult, ...spawnedResult]
          .flatMap((result) => result.status === 'rejected' ? [result.reason] : []);
        if (failures.length > 0) throw new AggregateError(failures, 'management cleanup failed');
        await cleanupStep('fixture', async () => {
          if (fixture === null) return false;
          await removeFixture(fixture);
          return true;
        });
      },
    );
  } catch (error) {
    failure = error;
  }

  {
    try {
      results.cleanup.ingress_alive_after_cleanup = (results.processes.ingress as number[]).filter(processAlive);
    } catch (error) {
      const message = `ingress cleanup verification: ${sanitize(errorText(error))}`;
      harnessErrors.push(message);
      results.cleanup.ingress_alive_after_cleanup_error = message;
      if (failure === null) failure = error;
    }

    results.ports.management = managementPort;
    results.ports.public = publicPort;
    results.ports.upstream = upstreamPort;
    results.revision = revision;
    try {
      await writeFile(join(EVIDENCE_DIR, 'results.json'), `${JSON.stringify(results, null, 2)}\n`, 'utf8');
    } catch (error) {
      const message = `results write: ${sanitize(errorText(error))}`;
      harnessErrors.push(message);
      if (failure === null) failure = error;
    }
  }

  if (failure !== null) throw failure;
}

try {
  await main();
  console.log(`management-port-playwright-real passed; evidence: ${EVIDENCE_DIR}`);
} catch (error) {
  console.error(`management-port-playwright-real failed: ${sanitize(errorText(error))}`);
  process.exitCode = 1;
}
