import { createHash } from 'node:crypto';
import { readFile, stat, writeFile, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { buildRelations, phases, selectTests, validatePlan, type Phase, type Snapshot, type TestPlan } from './test-selection';

export async function git(root: string, args: string[], input?: string): Promise<Buffer> {
  const child = Bun.spawn(['git', ...args], { cwd: root, stdin: input === undefined ? 'ignore' : new TextEncoder().encode(input), stdout: 'pipe', stderr: 'pipe' });
  const [stdout, stderr, code] = await Promise.all([new Response(child.stdout).arrayBuffer(), new Response(child.stderr).text(), child.exited]);
  if (code !== 0) throw new Error(`git ${args[0]} failed (${code}): ${stderr.trim()}`);
  return Buffer.from(stdout);
}
const entries = (buffer: Buffer): string[] => buffer.toString('utf8').split('\0').filter(Boolean);
async function commit(root: string, ref: string): Promise<string> {
  return (await git(root, ['rev-parse', '--verify', '--end-of-options', `${ref}^{commit}`])).toString().trim();
}
export function diffPaths(buffer: Buffer): string[] {
  const tokens = entries(buffer), paths: string[] = [];
  for (let index = 0; index < tokens.length;) {
    const status = tokens[index++]!;
    const count = /^[RC]\d+$/.test(status) ? 2 : /^[AMDUTX]$/.test(status) ? 1 : 0;
    if (!count || index + count > tokens.length) throw new Error(`Invalid git diff status: ${status}`);
    paths.push(...tokens.slice(index, index + count)); index += count;
  }
  return [...new Set(paths)].sort();
}
const sourceFile = (path: string): boolean => /\.[cm]?[jt]sx?$|\.svelte$/.test(path) || /^plugins\/[^/]+\/manifest\.json$/.test(path);
// These tracked sources are overwritten by the build and transferred with platform artifacts.
// Their generated bytes do not identify a source checkout; every other change still invalidates a CI plan.
const generatedSources = ['packages/core/src/ui/assets.ts', 'packages/ui/src/components/native-widgets/generated.ts'];
async function committedSnapshot(root: string, sha: string): Promise<{ paths: string[]; source: Snapshot }> {
  const paths = entries(await git(root, ['ls-tree', '-r', '--name-only', '-z', sha]));
  if (paths.some(path => /[\r\n]/.test(path))) throw new Error('Git paths containing newlines are unsupported');
  const wanted = paths.filter(sourceFile), source: Snapshot = Object.fromEntries(paths.map(path => [path, '']));
  if (!wanted.length) return { paths, source };
  const objects = await git(root, ['cat-file', '--batch'], wanted.map(path => `${sha}:${path}\n`).join(''));
  let offset = 0;
  for (const path of wanted) {
    const end = objects.indexOf(10, offset), header = objects.subarray(offset, end).toString();
    const match = header.match(/^[a-f0-9]+ blob (\d+)$/);
    if (end < 0 || !match) throw new Error(`Cannot read Git blob: ${path}`);
    const length = Number(match[1]); offset = end + 1;
    source[path] = objects.subarray(offset, offset + length).toString('utf8'); offset += length + 1;
  }
  return { paths, source };
}
export async function workingSnapshot(root: string): Promise<{ paths: string[]; source: Snapshot; tree: string }> {
  const listed = [...new Set(entries(await git(root, ['ls-files', '--cached', '--others', '--exclude-standard', '-z'])))].sort();
  const source: Snapshot = {}, paths: string[] = [], hash = createHash('sha256');
  for (const path of listed) {
    let content: Buffer, mode: number;
    try { content = await readFile(resolve(root, path)); mode = (await stat(resolve(root, path))).mode & 0o111; }
    catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') continue; throw error; }
    paths.push(path); hash.update(path + '\0' + mode + '\0' + content.length + '\0'); hash.update(content);
    source[path] = sourceFile(path) ? content.toString('utf8') : '';
  }
  return { paths, source, tree: hash.digest('hex') };
}
export async function createPlan(root: string, options: { base: string; committed?: boolean; full?: boolean; head?: string }): Promise<TestPlan> {
  const base = await commit(root, options.base), testCommit = await commit(root, 'HEAD');
  const head = options.head ? await commit(root, options.head) : undefined;
  const before = await committedSnapshot(root, base);
  const after = options.committed ? await committedSnapshot(root, testCommit) : await workingSnapshot(root);
  const changed = diffPaths(await git(root, ['diff', '--name-status', '-z', '--find-renames', base, ...(options.committed ? [testCommit] : []), '--']));
  if (!options.committed) changed.push(...entries(await git(root, ['ls-files', '--others', '--exclude-standard', '-z'])));
  const tree = 'tree' in after && typeof after.tree === 'string' ? after.tree : (await git(root, ['rev-parse', `${testCommit}^{tree}`])).toString().trim();
  return selectTests({ paths: after.paths, changed, relations: buildRelations(before.source, after.source), base, testCommit, tree, head, full: options.full });
}
export function testCommand(plan: TestPlan, phase: Phase, shard?: string): string[] {
  if (shard && !/^[1-9]\d*\/[1-9]\d*$/.test(shard)) throw new Error('Shard must be i/n');
  if (shard) { const [index, count] = shard.split('/').map(Number); if (index! > count!) throw new Error('Shard index exceeds count'); }
  return [process.execPath, 'test', '--isolate', ...(shard ? [`--shard=${shard}`] : []), ...plan.files[phase].map(file => `./${file}`)];
}
async function runCommand(root: string, argv: string[]): Promise<number> {
  const child = Bun.spawn(argv, { cwd: root, stdin: 'inherit', stdout: 2, stderr: 2 });
  return child.exited;
}
async function runPhase(root: string, plan: TestPlan, phase: Phase, shard?: string, record?: string): Promise<number> {
  const argv = testCommand(plan, phase, shard), started = performance.now();
  const timings = record ? resolve(root, record + '.timings.json') : undefined;
  if (timings) {
    // Never feed previous measurements to native sharding: every shard starts with the same inputs.
    await rm(timings, { force: true });
    argv.splice(3, 0, `--timings=${timings}`, '--update-timings');
  }
  let status = 0;
  try { if (plan.files[phase].length) status = await runCommand(root, argv); }
  catch (error) { status = 1; throw error; }
  finally {
    let executed: string[] = [];
    if (timings && plan.files[phase].length) {
      try {
        const measured = JSON.parse(await readFile(timings, 'utf8'));
        if (measured.version !== 1 || !measured.files) throw new Error('Invalid native test timings');
        executed = Object.keys(measured.files).map(file => file.replace(/^\.\//, '')).sort();
      } catch (error) { if (!status) throw error; }
    }
    if (record) await writeFile(resolve(root, record), JSON.stringify({ phase, files: plan.files[phase], executed, commit: plan.testCommit, tree: plan.tree,
      ...(shard ? { shard } : {}), elapsed: Math.round(performance.now() - started), status }, null, 2) + '\n');
  }
  return status;
}
const help = `Usage: bun scripts/checks/select-tests.ts --base REF [--committed] [--full] [--head REF] [--output FILE] [--run]
       bun scripts/checks/select-tests.ts --plan FILE --phase unit|integration|browser [--shard i/n] [--record FILE]

Default output is JSON only. Local plans include staged, unstaged and unignored untracked files.
--committed compares base to the actual clean checkout commit; --head records source-head metadata.
--run builds once, then runs selected unit/integration/browser files in order.
--plan consumes an existing plan without selection or build, and checks its commit/tree identity.
Records list the explicit candidate files passed to Bun; --shard uses Bun's native partitioning.
Output and record files must be outside the repository to preserve the planned working tree.
`;
export async function main(argv = process.argv.slice(2), cwd = process.cwd()): Promise<number> {
  const options: Record<string, string | boolean> = {};
  const flags = new Set(['committed','full','run','help']);
  const values = new Set(['base','head','output','plan','phase','shard','record']);
  for (let i = 0; i < argv.length; i++) {
    const name = argv[i]!.replace(/^--/, '');
    if (!argv[i]!.startsWith('--') || options[name] !== undefined || (!flags.has(name) && !values.has(name))) throw new Error(`Unknown or duplicate option: ${argv[i]}`);
    if (flags.has(name)) options[name] = true;
    else { const value = argv[++i]; if (!value || value.startsWith('--')) throw new Error(`Missing value: --${name}`); options[name] = value; }
  }
  if (options.help) { process.stdout.write(help); return 0; }
  const root = (await git(cwd, ['rev-parse', '--show-toplevel'])).toString().trim();
  for (const name of ['output','record']) if (options[name] && (resolve(root, String(options[name])) === root || resolve(root, String(options[name])).startsWith(root + '/'))) throw new Error(`--${name} must be outside the repository`);
  if (options.plan) {
    if (['base','head','committed','full','run','output'].some(key => options[key])) throw new Error('--plan cannot be combined with selection options');
    const phase = options.phase as Phase;
    if (!phases.includes(phase)) throw new Error('--plan requires --phase unit|integration|browser');
    const snapshot = await workingSnapshot(root);
    const plan = validatePlan(JSON.parse(await readFile(resolve(root, String(options.plan)), 'utf8')), snapshot.paths);
    if (await commit(root, 'HEAD') !== plan.testCommit) throw new Error('Plan commit does not match checkout');
    if (plan.tree.length === 64) {
      if (snapshot.tree !== plan.tree) throw new Error('Plan working tree has changed');
    } else {
      if ((await git(root, ['rev-parse', 'HEAD^{tree}'])).toString().trim() !== plan.tree ||
          (await git(root, ['status','--porcelain','-z','--untracked-files=all','--','.',...generatedSources.map(path => `:(exclude)${path}`)])).length) throw new Error('Plan committed tree has changed');
    }
    return runPhase(root, plan, phase, options.shard as string | undefined, options.record as string | undefined);
  }
  if (!options.base) throw new Error('--base is required');
  if (options.phase || options.shard || options.record) throw new Error('--phase, --shard and --record require --plan');
  const plan = await createPlan(root, { base: String(options.base), committed: Boolean(options.committed), full: Boolean(options.full), head: options.head as string | undefined });
  const json = JSON.stringify(plan, null, 2) + '\n';
  if (options.output) await writeFile(resolve(root, String(options.output)), json);
  process.stdout.write(json);
  if (options.run && plan.build) {
    if (options.committed && (await git(root, ['status','--porcelain','-z','--untracked-files=all'])).length) throw new Error('--committed --run requires a clean working tree');
    const build = await runCommand(root, [process.execPath, 'run', 'build']); if (build) return build;
    for (const phase of phases) { const status = await runPhase(root, plan, phase); if (status) return status; }
  }
  return 0;
}
if (import.meta.main) {
  try { process.exitCode = await main(); }
  catch (error) { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; }
}
