name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Prepare test environment
        run: cp config.example.json config.json

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build UI assets
        run: bun run build:ui && bun run bundle:ui

      - name: Run tests
        run: bun test
